Repository do-gather-challenge/do-gather, pull requests merged in 2025-03, with the labels that each got.

#10 Feature/#7 빌드 테스트 깃헙액션
  .github/workflows/build_test.yml
  package.json
  src/app/(client)/challenge/[id]/page.tsx
  src/app/(client)/challenge/page.tsx
  src/app/(client)/challenge/post/page.tsx
  src/app/(client)/home/page.tsx
  src/app/(client)/my-page/page.tsx
Labels: ⚙ Setting

#18 Feature/#16 next version
  next.config.js
  package.json
  pnpm-lock.yaml
  src/app/(client)/layout.tsx
Labels: ⚙ Setting, 🎨 Design

#11 Feat/#5 my-page 마이페이지 기본 UI 셋업
  package.json
  pnpm-lock.yaml
  public/images/default_profile.png
  src/app/(client)/my-page/page.tsx
  src/components/my-page/my-page-edit-profile.tsx
  src/components/my-page/my-page-my-challenge.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/tabs.tsx
Labels: 🎨 Design

#21 Feature/#4 기본 UI 및 기능 구현
  public/images/about-etc.webp
  public/images/about-exercise.jpg
  public/images/about-study.jpeg
  public/images/logo.png
  src/app/page.tsx
Labels: 🎨 Design, ✨ Feature

#13 Feature/#2 common components
  package.json
  pnpm-lock.yaml
  public/React.png
  src/components/features/challenges/challenge-card.tsx
  src/components/ui/avatar.tsx
  src/components/ui/card.tsx
  src/components/ui/rounded-image.tsx
  src/components/ui/tag.tsx
Labels: 🎨 Design, ✨ Feature

#15 Feature/#3 challenge post UI
  package.json
  pnpm-lock.yaml
  src/app/(client)/challenge/post/page.tsx
  src/app/(client)/challenges/[id]/page.tsx
  src/app/(client)/challenges/page.tsx
  src/app/(client)/challenges/post/page.tsx
  src/app/globals.css
  src/components/features/challenges/post/challenge-post-button-group.tsx
  src/components/features/challenges/post/challenge-post-date-modal.tsx
  src/components/features/challenges/post/challenge-post-date-picker.tsx
  src/components/features/challenges/post/challenge-post-image-uploader.tsx
  src/components/features/challenges/post/challenge-post-input.tsx
  src/components/features/challenges/post/challenge-post-selector.tsx
  src/components/ui/input.tsx
  src/components/ui/textarea.tsx
  src/constants/challenge.constants.ts
  src/lib/hooks/use-challenge-form.ts
  src/lib/utils/post.util.ts
Labels: 🎨 Design, ✨ Feature

#19 Feature/#9 auth UI 및 기본 파일 세팅
  package.json
  pnpm-lock.yaml
  public/images/ICON_GITHUB.png
  public/images/ICON_GOOGLE.png
  src/app/(client)/@auth/(.)sign-in/page.tsx
  src/app/(client)/@auth/(.)sign-up/page.tsx
  src/app/(client)/@auth/default.tsx
  src/app/(client)/home/page.tsx
  src/app/(client)/layout.tsx
  src/app/(client)/sign-in/page.tsx
  src/app/(client)/sign-up/page.tsx
  src/app/api/auth/callback/route.ts
  src/components/features/auth/auth-sign-in-form.tsx
  src/components/features/auth/auth-sign-up-form.tsx
  src/components/ui/form.tsx
  src/components/ui/label.tsx
  src/lib/supabase/client.ts
  src/lib/supabase/middleware.ts
  src/lib/supabase/server.ts
Labels: ⚙ Setting, 🎨 Design, ✨ Feature

#23 Design/#12 challenge detail page
  public/images/default-challenge.jpg
  public/images/icon-kakao-talk.png
  src/app/(client)/challenges/[id]/page.tsx
  src/app/(client)/layout.tsx
  src/app/globals.css
  src/components/features/challenges/detail/challenge-detail-back-button.tsx
  src/components/features/challenges/detail/challenge-detail-complete-button.tsx
  src/components/features/challenges/detail/challenge-detail-info-field.tsx
  src/components/features/challenges/detail/challenge-detail-join-button.tsx
  src/components/features/challenges/detail/challenge-detail-share-button.tsx
  src/components/features/challenges/post/challenge-post-button-group.tsx
  src/components/features/challenges/post/challenge-post-input.tsx
  src/components/features/challenges/post/challenge-post-selector.tsx
  src/constants/image.constant.ts
  src/lib/api/challenge.api.ts
  src/lib/hooks/use-challenge-form.ts
  src/lib/utils/validate.util.ts
  src/types/challenge-category.type.ts
  src/types/challenge.type.ts
Labels: 🎨 Design, ✨ Feature

#22 Feature/#20 auth
  src/app/(client)/@auth/(.)sign-in/page.tsx
  src/components/features/auth/auth-input-field.tsx
  src/components/features/auth/auth-sign-in-form.tsx
  src/components/features/auth/auth-sign-up-form.tsx
  src/constants/auth-schema.constant.ts
  src/lib/hooks/use-sign-in-form.ts
  src/lib/hooks/use-sign-up-form.ts
Labels: ✨ Feature

#29 Feature/#28 tanstack query settings
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/lib/providers/TQProvider.tsx
Labels: ⚙ Setting

#30 Feature/#14 home페이지 중 인기 챌린지 구현
  next.config.js
  package.json
  pnpm-lock.yaml
  public/images/icon-deadline.png
  src/app/(client)/home/page.tsx
  src/components/features/challenges/home/challenge-carousel-card.tsx
  src/components/features/challenges/home/challenge-popular.tsx
  src/components/ui/carousel.tsx
  src/components/ui/start-date-badge.tsx
  src/lib/utils/calculate-days-left.util.ts
  src/types/challenge-status.type.ts
Labels: 🎨 Design, 📬 API, ✨ Feature

#26 Feature/#17 challenge post api
  .github/workflows/build_test.yml
  package.json
  pnpm-lock.yaml
  src/app/(client)/challenges/post/page.tsx
  src/components/features/challenges/post/challenge-post-button-group.tsx
  src/components/features/challenges/post/challenge-post-date-modal.tsx
  src/components/features/challenges/post/challenge-post-date-picker.tsx
  src/components/features/challenges/post/challenge-post-image-uploader.tsx
  src/components/features/challenges/post/challenge-post-input.tsx
  src/components/features/challenges/post/challenge-post-selector.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/popover.tsx
  src/constants/challenge-post.constants.ts
  src/constants/challenge.constants.ts
  src/constants/files.constant.ts
  src/lib/api/challenge-post.api.ts
  src/lib/api/storage.api.ts
  src/lib/hooks/use-challenge-form.ts
  src/lib/supabase/client.ts
  src/lib/utils/post.util.ts
  src/lib/utils/validate.util.ts
  src/types/challenge-post.type.ts
Labels: 📬 API, ✨ Feature

#34 Feature/#25 challenge detail page button
  next.config.ts
  src/app/(client)/challenges/[id]/page.tsx
  src/app/layout.tsx
  src/components/features/challenges/detail/challenge-detail-back-button.tsx
  src/components/features/challenges/detail/challenge-detail-complete-button.tsx
  src/components/features/challenges/detail/challenge-detail-join-button.tsx
  src/components/features/challenges/detail/challenge-detail-share-button.tsx
  src/constants/breakpoints.ts
  src/constants/env.constant.ts
  src/constants/query-keys.ts
  src/lib/api/challenge.api.ts
  src/lib/api/completed.api.ts
  src/lib/api/my-challenge.api.ts
  src/lib/api/participant.api.ts
  src/lib/queries/useGetMyInProgressChallengesQuery.ts
  src/lib/utils/transform.util.ts
  src/types/challenge.type.ts
  src/types/common.type.ts
Labels: 📬 API, ✨ Feature

#39 Fix/#38 remove duplicated files
  src/constants/query-keys.constant.ts
  src/constants/query-keys.ts
  src/lib/queries/use-get-my-in-progress-challenges-query.ts
  src/lib/queries/useGetMyInProgressChallengesQuery.ts
Labels: 🐞 BugFix

#46 Chore/#41 loading page
  public/images/loading-spinner.svg
  src/app/loading.tsx
  src/components/ui/loading-skeleton.tsx
Labels: 🎨 Design

#42 Feature/#33 challenge post update
  src/app/(client)/challenges/post/[id]/page.tsx
  src/app/(client)/challenges/post/page.tsx
  src/components/features/challenges/post/challenge-post-button-group.tsx
  src/components/features/challenges/post/challenge-post-date-picker.tsx
  src/components/features/challenges/post/challenge-post-form.tsx
  src/components/features/challenges/post/challenge-post-image-uploader.tsx
  src/constants/challenge-post.constants.ts
  src/lib/api/challenge-post.api.ts
  src/lib/hooks/use-challenge-form.ts
  src/lib/hooks/use-challenge-post-mutation.ts
  src/lib/utils/post.util.ts
  src/lib/utils/validate.util.ts
  src/types/challenge-post.type.ts
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#43 Feature/#24 my-page 기능구현 중간PR
  src/app/(client)/my-page/page.tsx
  src/components/features/challenges/challenge-card.tsx
  src/components/my-page/my-page-edit-profile.tsx
  src/components/my-page/my-page-my-challenge.tsx
  src/components/my-page/my-page-my-challenges-completions-today.tsx
  src/components/my-page/my-page-my-completed-challenges.tsx
  src/components/my-page/my-page-my-in-progress-challenges.tsx
  src/constants/challenge-post.constants.ts
  src/constants/my-page-constant.ts
  src/constants/query-keys.constant.ts
  src/lib/api/completed.api.ts
  src/lib/api/my-challenge.api.ts
  src/lib/queries/use-get-my-challenges-completions-today-query.ts
  src/lib/queries/use-get-my-completed-challenges-query.ts
  src/lib/utils/transform.util.ts
  src/types/my-page-type.ts
Labels: ✨ Feature

#49 Refact/#44 auth
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/(client)/challenges/[id]/page.tsx
  src/app/(client)/default.tsx
  src/app/(client)/layout.tsx
  src/app/page.tsx
  src/components/features/auth/auth-sign-in-form.tsx
  src/components/features/auth/auth-sign-up-form.tsx
  src/components/features/auth/auth-toggle-link.tsx
  src/components/features/challenges/home/challenge-carousel-card.tsx
  src/components/features/challenges/post/challenge-post-button-group.tsx
  src/constants/app-url.constant.ts
  src/lib/hooks/use-close-modal.ts
  src/lib/supabase/server.ts
  src/middleware.ts
Labels: 🎨 Design, 🔨 Refactor, ✨ Feature

#53 Feature/#35 challenge log section
  src/app/(client)/challenges/[id]/page.tsx
  src/components/features/challenges/detail/challenge-detail-complete-button.tsx
  src/components/features/challenges/detail/challenge-detail-join-button.tsx
  src/components/features/challenges/detail/challenge-detail-log-section.tsx
  src/lib/api/challenge-completed.api.ts
  src/lib/api/challenge-logs.api.ts
  src/lib/api/challenge-participant.api.ts
  src/lib/api/participant.api.ts
  src/lib/api/user-Info.api.ts
  src/lib/utils/transform.util.ts
  src/types/challenge-category.type.ts
  src/types/challenge-log.type.ts
  src/types/common.type.ts
  src/types/user-info.types.ts
Labels: 📬 API, ✨ Feature

#56 Feature/#54 home page design
  src/app/(client)/home/page.tsx
  src/components/features/challenges/home/challenge-home-find.tsx
  src/components/features/challenges/home/challenge-home-participation.tsx
  src/components/features/challenges/home/challenge-popular.tsx
Labels: 🎨 Design

#59 Bugfix/#58 challenge log antipattern
  src/components/features/challenges/detail/challenge-detail-log-section.tsx
Labels: 🐞 BugFix

#64 Bugfix/#63 social login error
  src/app/api/auth/callback/route.ts
  src/components/features/auth/auth-sign-in-form.tsx
  src/constants/env.constant.ts
Labels: 🐞 BugFix

#65 Feature/#52 post page UI
  src/app/(client)/challenges/post/[id]/page.tsx
  src/components/features/challenges/post/challenge-post-button-group.tsx
  src/components/features/challenges/post/challenge-post-form.tsx
  src/components/features/challenges/post/challenge-post-image-uploader.tsx
  src/components/features/challenges/post/challenge-post-input.tsx
  src/components/features/challenges/post/challenge-post-selector.tsx
  src/constants/challenge-post.constants.ts
  src/lib/api/challenge-post.api.ts
  src/lib/hooks/use-challenge-post-mutation.ts
  src/lib/utils/post.util.ts
Labels: 🎨 Design, 🔨 Refactor

#66 Feature/#60 route from home
  src/app/(client)/home/page.tsx
  src/components/features/challenges/challenge-card-skeleton.tsx
  src/components/features/challenges/challenge-card.tsx
  src/components/features/challenges/home/challenge-home-find-filter.tsx
  src/components/features/challenges/home/challenge-home-find-filtered-list.tsx
  src/components/features/challenges/home/challenge-home-find.tsx
  src/components/features/challenges/home/challenge-home-participation-list.tsx
  src/lib/hooks/use-debounce.ts
  src/lib/queries/use-get-challenges-by-page-query.ts
  src/types/challenge-filter.type.ts
Labels: 🎨 Design, ✨ Feature

#70 Design/#69 react toastify
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/components/features/challenges/detail/challenge-detail-share-button.tsx
Labels: 🎨 Design, ✨ Feature

#73 Design/#72 not found page
  src/app/not-found.tsx
Labels: 🎨 Design, ✨ Feature

#68 Feature/#55 challenge log
  src/app/(client)/challenges/[id]/page.tsx
  src/components/features/challenges/detail/challenge-detail-log-content.tsx
  src/components/features/challenges/detail/challenge-detail-log-section.tsx
  src/lib/api/challenge-logs.api.ts
  src/lib/hooks/use-close-modal.ts
Labels: ✨ Feature

#67 Feature/#50 my-page 마이페이지 추가기능 구현
  src/app/(client)/my-page/page.tsx
  src/components/features/my-page/my-page-edit-profile.tsx
  src/components/features/my-page/my-page-my-challenge.tsx
  src/components/features/my-page/my-page-my-challenges-completions-today.tsx
  src/components/features/my-page/my-page-my-completed-challenges.tsx
  src/components/features/my-page/my-page-my-in-progress-challenges.tsx
  src/constants/error-message.constant.ts
  src/constants/my-page-constant.ts
  src/lib/queries/use-get-my-challenges-completions-today-query.ts
  src/lib/queries/use-get-my-completed-challenges-query.ts
  src/lib/queries/use-get-my-in-progress-challenges-query.ts
  src/types/my-page-type.ts
Labels: 🔨 Refactor, ✨ Feature

#76 feat: #75 유저가 챌린지 모든 요일을 선택했는지의 상태에 맞게 isEveryDayChecked를 업데이트하는 기능
  src/app/(client)/challenges/post/[id]/page.tsx
  src/components/features/challenges/post/challenge-post-selector.tsx
  src/lib/api/challenge-post.api.ts
Labels: ✨ Feature

#78 Fix/#77 card rounded modify
  src/components/features/challenges/challenge-card.tsx
Labels: 🎨 Design

#79 Refact/#74 전역 페이지 toastify 적용하기 및 하드코딩 제거
  src/components/features/auth/auth-sign-in-form.tsx
  src/components/features/challenges/post/challenge-post-button-group.tsx
  src/components/features/my-page/my-page-edit-profile.tsx
  src/components/layouts/header.tsx
  src/lib/api/user-Info.api.ts
  src/lib/hooks/use-sign-in-form.ts
  src/lib/hooks/use-sign-up-form.ts
Labels: 🔨 Refactor

#80 Docs/#71 readme
  README.md
Labels: 📃 Docs
